### PR TITLE
Consulter la liste des villas

### PR DESCRIPTION
**Pull request by Murihano**
Mise en relation des pages
html et css

### CODE REVIEW

**Review by AhmadSAFAR — APPROVED** [review]
c'est bon :)

**Review by RomainClair — CHANGES_REQUESTED** [review]
There is no constraints to validate the form. Anything can be added as a villa.

You probably should type your form fields

**Review by AhmadSAFAR — APPROVED** [review]
ok

**Review by AhmadSAFAR — APPROVED** [review]
ok!

**Review by RomainClair — APPROVED** [review]

**Pull request merged**
